[build]
  publish = "app/static"
  command = "echo 'Static files ready'"

[[redirects]]
  from = "/api/*"
  to = "https://dugun-drive-1.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18" 