services:
  - type: web
    name: dugun-drive-api
    env: python
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GOOGLE_CREDENTIALS_FILE
        value: credentials.json
      - key: GOOGLE_TOKEN_FILE
        value: token.json 