services:
  - type: web
    name: dugun-drive-api
    env: python
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: GOOGLE_CREDENTIALS_FILE
        value: credentials.json
      - key: GOOGLE_TOKEN_FILE
        value: token.json
      - key: ENVIRONMENT
        value: production
      - key: API_TITLE
        value: Düğün Drive API
      - key: API_VERSION
        value: 1.0.0
      - key: API_DESCRIPTION
        value: Düğün Drive integration API
      - key: ALLOWED_ORIGINS
        value: '["http://localhost:3000","http://localhost:8080","http://localhost:8000","http://127.0.0.1:8000","https://*.netlify.app","https://*.onrender.com","https://dugun-drive.netlify.app","https://dugun-drive-api.onrender.com"]'
    buildFilter:
      paths:
        - requirements.txt
        - render.yaml
        - render-build.sh
        - app/**
        - env.production
        - credentials.json 